<div class="container w-50">
<h2 class="text-center mt-5">
View Index File
</h2>

<h2>Sign up using this form</h2>

<?php echo $this->tag->form("index/adduser"); ?>

    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton("Register"); ?>
    </p>

</form>


</div>